### ISSUE TITLE
Data cannot be displayed when viewed with "Local Enterprise Partnerships"

### ISSUE THREAD

**Issue by VT-UKPN** [odileeds/ukpowernetworks#23]
Data can be viewed with Local Authorities, Counties and UA and LSOA but keeps loading when "Local Enterprise Partnerships" is selected.

**Comment by slowe** [comment]
@VT-UKPN The code was trying to work out a text label for Greater Lincolnshire but was being passed `null` rather than a value and that stopped the code from continuing. We seem to be including Greater Lincolnshire (E37000014) with one LSOA (E01026278) in the file [2021-DFES/data/lsoa2lep-compact.json](../tree/main/2021-DFES/data/lsoa2lep-compact.json) but the data files don't include it. I've added a check in the text label function so that any non-number value no longer breaks the code. It may be that we can remove Greater Lincolnshire from the lookup.

**Comment by VT-UKPN** [comment]
Thanks for the help @slowe , it works well now.
