### ISSUE TITLE
Showing data by LSOAs for specific Local Authorities

### ISSUE THREAD

**Issue by ash001j** [odileeds/ukpowernetworks#5]
Need to discuss the functionality of viewing individual LSOAs within the map

**Comment by slowe** [comment]
I've changed my mind on this because having some LADs presented by LSOA or not and the interaction states (turning it on/off) quickly get quite complicated. So I've tried using the ONS Super-generalised boundaries and saved these to 3 decimal-place-precision in the coordinates (~50-100m). The result is a big file but just about manageable. If we don't need the names of the LSOAs (for the search and the title in the popups) then we can shrink the file a bit more. To stop the borders dominating, I've hidden the LSOA borders. Hovering over them shows the borders (as it does in the other layers). If we go back to having an LSOA layer we also remove the need to have files with cuts of LSOA by LAD/LEP/county.

**Comment by ash001j** [comment]
Closed
